In [3]:
import numpy as np

# Mathematical Operation

In [4]:
x=np.array([1,2,3,4,5,6,7])

In [5]:
np.sqrt(x)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131])

In [11]:
np.positive(x)

array([1, 2, 3, 4, 5, 6, 7])

In [12]:
np.power(x,2)

array([ 1,  4,  9, 16, 25, 36, 49], dtype=int32)

In [13]:
np.log(x)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015])

In [14]:
np.sin(x)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ])

In [30]:
y=[2,3,4,5,6,7,19]

In [34]:
np.maximum(x,y)

array([ 2,  3,  4,  5,  6,  7, 19])

# np.where()

In [36]:
np.where(x==2,"yes","no")

array(['no', 'yes', 'no', 'no', 'no', 'no', 'no'], dtype='<U3')

In [44]:
payment=np.array([0,-1,10000000,5000000])

In [45]:
np.where(payment<=0,250000,payment)

array([  250000,   250000, 10000000,  5000000])

# More Operation On Numpy Array

In [46]:
np.mean(x)

4.0

In [47]:
x.mean()

4.0

In [48]:
num=np.array([7,7,9,9,1,22,2,2,22])

In [49]:
num.max()

22

In [50]:
num.mean()

9.0

In [51]:
num.cumsum()

array([ 7, 14, 23, 32, 33, 55, 57, 59, 81], dtype=int32)

In [52]:
num.cumprod()

array([      7,      49,     441,    3969,    3969,   87318,  174636,
        349272, 7683984], dtype=int32)

In [55]:
num1= num>7

In [56]:
num1

array([False, False,  True,  True, False,  True, False, False,  True])

In [57]:
num1.sum()

4

In [58]:
num1.any()

True

In [59]:
num1.all()

False

In [60]:
num1.sort()

In [61]:
num.sort()

In [62]:
num1

array([False, False, False, False, False,  True,  True,  True,  True])

In [64]:
num

array([ 1,  2,  2,  7,  7,  9,  9, 22, 22])

In [67]:
np.unique(num)

array([ 1,  2,  7,  9, 22])

In [2]:
import numpy as np

In [3]:
i=np.array([22,11,33,44,55,55,11,22])

In [4]:
i.cumsum()

array([ 22,  33,  66, 110, 165, 220, 231, 253], dtype=int32)

In [5]:
i.cumprod()

array([         22,         242,        7986,      351384,    19326120,
        1062936600, -1192599288,  -467380560], dtype=int32)

In [6]:
i2=i>11

In [7]:
i2

array([ True, False,  True,  True,  True,  True, False,  True])

In [8]:
i2.sum()

6

In [9]:
i2.all()

False

In [10]:
i2.any()

True

In [13]:
np.unique(i)

array([11, 22, 33, 44, 55])

In [21]:
import numpy as np

In [28]:
np.array(x)

array([22, 33, 44,  5, 66, 77])

In [41]:
x=[22,33,44,5,66,77]

In [42]:
np.array(x)

array([22, 33, 44,  5, 66, 77])

In [43]:
np.save("testx.py",x)

In [44]:
loadx=np.load('testx.npy')

In [45]:
loadx

array([22, 33, 44,  5, 66, 77])

In [46]:
y=[22,11,33,44]

In [47]:
np.savez('testxy',x,y)

In [51]:
loadxy=np.load('testxy.npz')

In [52]:
np.unique(x)

array([ 5, 22, 33, 44, 66, 77])

# Metrics Operation

In [54]:
x=np.random.randn(3,3)

In [55]:
y=np.random.randn(3,3)

In [56]:
x.dot(y)

array([[-1.07124150e+00, -4.39928536e+00, -2.25745635e+00],
       [ 1.50738267e-01,  9.16873970e-02, -2.01650284e-03],
       [ 1.28590499e+00,  4.36029593e+00,  2.18092567e+00]])

In [57]:
x.trace()

-2.7389210637019565

# Using Random Key Word

In [62]:
np.random.seed(7)

In [64]:
np.random.normal(size=(3,3))

array([[ 1.69052570e+00, -4.65937371e-01,  3.28201637e-02],
       [ 4.07516283e-01, -7.88923029e-01,  2.06557291e-03],
       [-8.90385858e-04, -1.75472431e+00,  1.01765801e+00]])

In [65]:
np.random.uniform(size=(6,6))

array([[0.38094113, 0.06593635, 0.2881456 , 0.90959353, 0.21338535,
        0.45212396],
       [0.93120602, 0.02489923, 0.60054892, 0.9501295 , 0.23030288,
        0.54848992],
       [0.90912837, 0.13316945, 0.52341258, 0.75040986, 0.66901324,
        0.46775286],
       [0.20484909, 0.49076589, 0.37238469, 0.47740115, 0.36589039,
        0.83791799],
       [0.76864751, 0.31399468, 0.57262533, 0.27604905, 0.45284293,
        0.35297837],
       [0.65739946, 0.37035108, 0.45909298, 0.71932412, 0.41299183,
        0.90642327]])

In [67]:
x=np.random.randn(4,5)

In [68]:
np.shape(x)

(4, 5)

# Reshap

In [69]:
x.reshape((2,2,5))

array([[[-1.90636988, -0.09961063,  1.6995373 , -0.38342312,
         -0.88985686],
        [-1.19359192, -1.05001681, -0.30019374, -1.17998209,
          1.49763912]],

       [[-0.28263524,  0.10864837,  1.43823952,  1.50331852,
         -0.21273297],
        [ 0.33197422,  0.73502658, -0.19285546, -1.77801285,
          0.6547057 ]]])

In [70]:
x


array([[-1.90636988, -0.09961063,  1.6995373 , -0.38342312, -0.88985686],
       [-1.19359192, -1.05001681, -0.30019374, -1.17998209,  1.49763912],
       [-0.28263524,  0.10864837,  1.43823952,  1.50331852, -0.21273297],
       [ 0.33197422,  0.73502658, -0.19285546, -1.77801285,  0.6547057 ]])

In [73]:
x.reshape((2,2,-1), order="C")

array([[[-1.90636988, -0.09961063,  1.6995373 , -0.38342312,
         -0.88985686],
        [-1.19359192, -1.05001681, -0.30019374, -1.17998209,
          1.49763912]],

       [[-0.28263524,  0.10864837,  1.43823952,  1.50331852,
         -0.21273297],
        [ 0.33197422,  0.73502658, -0.19285546, -1.77801285,
          0.6547057 ]]])

In [74]:
x.ravel()

array([-1.90636988, -0.09961063,  1.6995373 , -0.38342312, -0.88985686,
       -1.19359192, -1.05001681, -0.30019374, -1.17998209,  1.49763912,
       -0.28263524,  0.10864837,  1.43823952,  1.50331852, -0.21273297,
        0.33197422,  0.73502658, -0.19285546, -1.77801285,  0.6547057 ])

# Concetenation

In [75]:
x=[[1,2,3],[4,5,6]]

In [77]:
arr1=np.array(x)

In [78]:
y=[[11,12,13],[14,15,16]]

In [79]:
arr2=np.array(y)

In [80]:
np.concatenate((arr1,arr2),axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [14, 15, 16]])

In [81]:
np.concatenate((arr1,arr2),axis=1)

array([[ 1,  2,  3, 11, 12, 13],
       [ 4,  5,  6, 14, 15, 16]])

In [84]:
np.vstack((arr1,arr2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [14, 15, 16]])

In [85]:
np.hstack((arr1,arr2))

array([[ 1,  2,  3, 11, 12, 13],
       [ 4,  5,  6, 14, 15, 16]])

In [89]:
x=[1,2,3,4,5,6,7,8,14,0]

In [93]:
d=np.array(x)

# np.split()

In [96]:
np.split(d,[3,7])

[array([1, 2, 3]), array([4, 5, 6, 7]), array([ 8, 14,  0])]

In [97]:
y=[[11,22,33],[44,55,66]]

In [99]:
d=np.array(y)

In [100]:
y

[[11, 22, 33], [44, 55, 66]]

In [103]:
np.split(d,[22,55])

[array([[11, 22, 33],
        [44, 55, 66]]),
 array([], shape=(0, 3), dtype=int32),
 array([], shape=(0, 3), dtype=int32)]

In [104]:
x

[1, 2, 3, 4, 5, 6, 7, 8, 14, 0]

In [105]:
numbers=np.array(x)

In [106]:
numbers

array([ 1,  2,  3,  4,  5,  6,  7,  8, 14,  0])

# Repeat & Tile

In [108]:
np.repeat(numbers,2)

array([ 1,  1,  2,  2,  3,  3,  4,  4,  5,  5,  6,  6,  7,  7,  8,  8, 14,
       14,  0,  0])

In [109]:
np.tile(numbers,4)

array([ 1,  2,  3,  4,  5,  6,  7,  8, 14,  0,  1,  2,  3,  4,  5,  6,  7,
        8, 14,  0,  1,  2,  3,  4,  5,  6,  7,  8, 14,  0,  1,  2,  3,  4,
        5,  6,  7,  8, 14,  0])

In [110]:
numbers

array([ 1,  2,  3,  4,  5,  6,  7,  8, 14,  0])

In [114]:
np.sort(numbers)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8, 14])

In [115]:
np.sqrt(numbers)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.74165739])

In [117]:
n=np.power(numbers,2)

In [118]:
n

array([  0,   1,   4,   9,  16,  25,  36,  49,  64, 196], dtype=int32)

In [119]:
numbers

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8, 14])

In [120]:
n

array([  0,   1,   4,   9,  16,  25,  36,  49,  64, 196], dtype=int32)

In [121]:
np.split(n,[3,8])

[array([0, 1, 4], dtype=int32),
 array([ 9, 16, 25, 36, 49], dtype=int32),
 array([ 64, 196], dtype=int32)]