# Numpy

In [1]:
import numpy as np

In [34]:
name = np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe','Bob'])

In [51]:
data = np.random.randn(8,5) 

In [52]:
data

array([[ 0.17078961,  0.80713622,  0.23009333,  0.4699486 , -0.84331796],
       [ 0.9190185 , -0.67176269,  0.05741559,  1.3392056 ,  0.36890901],
       [ 1.31154104,  0.15007974, -0.01489877, -0.44825623, -0.75663531],
       [ 0.15701634,  0.63358932, -0.58150681,  1.26451423,  1.02347256],
       [-1.7229625 , -1.14827025,  2.37901451, -1.07108051,  0.49397531],
       [-0.33691316,  1.1454866 ,  0.83145028, -0.99986261, -0.10851929],
       [-0.773142  , -0.54052058, -0.44596314,  0.16095458,  0.14553122],
       [-3.24457245,  0.48528436, -1.94773789, -0.63273039, -0.22542646]])

In [53]:
name == 'Joe'

array([False,  True, False, False, False,  True,  True, False])

In [54]:
data[name =='Bob']

array([[ 0.17078961,  0.80713622,  0.23009333,  0.4699486 , -0.84331796],
       [ 0.15701634,  0.63358932, -0.58150681,  1.26451423,  1.02347256],
       [-3.24457245,  0.48528436, -1.94773789, -0.63273039, -0.22542646]])

In [56]:
data[name != 'Bob']

array([[ 0.9190185 , -0.67176269,  0.05741559,  1.3392056 ,  0.36890901],
       [ 1.31154104,  0.15007974, -0.01489877, -0.44825623, -0.75663531],
       [-1.7229625 , -1.14827025,  2.37901451, -1.07108051,  0.49397531],
       [-0.33691316,  1.1454866 ,  0.83145028, -0.99986261, -0.10851929],
       [-0.773142  , -0.54052058, -0.44596314,  0.16095458,  0.14553122]])

In [57]:
data

array([[ 0.17078961,  0.80713622,  0.23009333,  0.4699486 , -0.84331796],
       [ 0.9190185 , -0.67176269,  0.05741559,  1.3392056 ,  0.36890901],
       [ 1.31154104,  0.15007974, -0.01489877, -0.44825623, -0.75663531],
       [ 0.15701634,  0.63358932, -0.58150681,  1.26451423,  1.02347256],
       [-1.7229625 , -1.14827025,  2.37901451, -1.07108051,  0.49397531],
       [-0.33691316,  1.1454866 ,  0.83145028, -0.99986261, -0.10851929],
       [-0.773142  , -0.54052058, -0.44596314,  0.16095458,  0.14553122],
       [-3.24457245,  0.48528436, -1.94773789, -0.63273039, -0.22542646]])

In [60]:
data[name == 'Bob',2:]      

array([[ 0.23009333,  0.4699486 , -0.84331796],
       [-0.58150681,  1.26451423,  1.02347256],
       [-1.94773789, -0.63273039, -0.22542646]])

In [61]:
name

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe', 'Bob'],
      dtype='<U4')

In [70]:
data[name == 'Bob',3:4]  

array([[ 0.4699486 ],
       [ 1.26451423],
       [-0.63273039]])

In [63]:
data

array([[ 0.17078961,  0.80713622,  0.23009333,  0.4699486 , -0.84331796],
       [ 0.9190185 , -0.67176269,  0.05741559,  1.3392056 ,  0.36890901],
       [ 1.31154104,  0.15007974, -0.01489877, -0.44825623, -0.75663531],
       [ 0.15701634,  0.63358932, -0.58150681,  1.26451423,  1.02347256],
       [-1.7229625 , -1.14827025,  2.37901451, -1.07108051,  0.49397531],
       [-0.33691316,  1.1454866 ,  0.83145028, -0.99986261, -0.10851929],
       [-0.773142  , -0.54052058, -0.44596314,  0.16095458,  0.14553122],
       [-3.24457245,  0.48528436, -1.94773789, -0.63273039, -0.22542646]])

In [74]:
data[3]

array([ 0.15701634,  0.63358932, -0.58150681,  1.26451423,  1.02347256])

In [76]:
data[3,2]  

-0.5815068068181728

In [77]:
data[[3,4,0,1]]

array([[ 0.15701634,  0.63358932, -0.58150681,  1.26451423,  1.02347256],
       [-1.7229625 , -1.14827025,  2.37901451, -1.07108051,  0.49397531],
       [ 0.17078961,  0.80713622,  0.23009333,  0.4699486 , -0.84331796],
       [ 0.9190185 , -0.67176269,  0.05741559,  1.3392056 ,  0.36890901]])

In [82]:
data[~(name == 'Bob')] 

array([[ 0.9190185 , -0.67176269,  0.05741559,  1.3392056 ,  0.36890901],
       [ 1.31154104,  0.15007974, -0.01489877, -0.44825623, -0.75663531],
       [-1.7229625 , -1.14827025,  2.37901451, -1.07108051,  0.49397531],
       [-0.33691316,  1.1454866 ,  0.83145028, -0.99986261, -0.10851929],
       [-0.773142  , -0.54052058, -0.44596314,  0.16095458,  0.14553122]])

In [96]:
mask = (name == 'Bob') | (name == 'Joe')

In [97]:
mask

array([ True,  True, False,  True, False,  True,  True,  True])

In [100]:
data<0  

array([[False, False, False, False,  True],
       [False,  True, False, False, False],
       [False, False,  True,  True,  True],
       [False, False,  True, False, False],
       [ True,  True, False,  True, False],
       [ True, False, False,  True,  True],
       [ True,  True,  True, False, False],
       [ True, False,  True,  True,  True]])

In [101]:
data

array([[ 0.17078961,  0.80713622,  0.23009333,  0.4699486 , -0.84331796],
       [ 0.9190185 , -0.67176269,  0.05741559,  1.3392056 ,  0.36890901],
       [ 1.31154104,  0.15007974, -0.01489877, -0.44825623, -0.75663531],
       [ 0.15701634,  0.63358932, -0.58150681,  1.26451423,  1.02347256],
       [-1.7229625 , -1.14827025,  2.37901451, -1.07108051,  0.49397531],
       [-0.33691316,  1.1454866 ,  0.83145028, -0.99986261, -0.10851929],
       [-0.773142  , -0.54052058, -0.44596314,  0.16095458,  0.14553122],
       [-3.24457245,  0.48528436, -1.94773789, -0.63273039, -0.22542646]])

In [102]:
data[data<0]

array([-0.84331796, -0.67176269, -0.01489877, -0.44825623, -0.75663531,
       -0.58150681, -1.7229625 , -1.14827025, -1.07108051, -0.33691316,
       -0.99986261, -0.10851929, -0.773142  , -0.54052058, -0.44596314,
       -3.24457245, -1.94773789, -0.63273039, -0.22542646])

In [108]:
data[data<0] = 0

In [109]:
data

array([[0.17078961, 0.80713622, 0.23009333, 0.4699486 , 0.        ],
       [0.9190185 , 0.        , 0.05741559, 1.3392056 , 0.36890901],
       [1.31154104, 0.15007974, 0.        , 0.        , 0.        ],
       [0.15701634, 0.63358932, 0.        , 1.26451423, 1.02347256],
       [0.        , 0.        , 2.37901451, 0.        , 0.49397531],
       [0.        , 1.1454866 , 0.83145028, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.16095458, 0.14553122],
       [0.        , 0.48528436, 0.        , 0.        , 0.        ]])

# Fancy Indexing

In [126]:
arr = np.empty((8,4))

In [127]:
for i in range(8):
    arr[i] = i

In [128]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [129]:
arr[4]

array([4., 4., 4., 4.])

In [130]:
arr[[4,3]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.]])

In [131]:
arr[[[4,6]],2:]

array([[[4., 4.],
        [6., 6.]]])

In [140]:
arr = np.arange(32).reshape((8,4))

In [142]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [146]:
arr[[1,5,7,2],[0,3,1,2]]

array([ 4, 23, 29, 10])

In [153]:
arr[[1,5,7,2]][:,[0,3,1,2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

# Array Transpose and Swapping Axes

In [154]:
arr.T

array([[ 0,  4,  8, 12, 16, 20, 24, 28],
       [ 1,  5,  9, 13, 17, 21, 25, 29],
       [ 2,  6, 10, 14, 18, 22, 26, 30],
       [ 3,  7, 11, 15, 19, 23, 27, 31]])

In [155]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

# Array-Oriented Programming with Array

In [157]:
arr.sort()

In [159]:
print(arr.sort())

None


In [160]:
arr = np.arange(24)

In [163]:
arr.reshape(6,-1) 

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [164]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [165]:
arr.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [166]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [167]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [168]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])